import type { TypographyVariantsOptions } from "@mui/material/styles";
import {
  fontFamily,
  fontSize,
  fontSizeDisplay,
  fontWeight,
  lineHeight,
} from "./fonts";

export const typography: TypographyVariantsOptions = {
  fontFamily: fontFamily.stack,
  fontSize: 14,
  fontWeightLight: fontWeight.regular,
  fontWeightRegular: fontWeight.regular,
  fontWeightMedium: fontWeight.medium,
  fontWeightBold: fontWeight.bold,
  h1: {
    fontFamily: fontFamily.stack,
    fontWeight: fontWeight.bold,
    fontSize: fontSizeDisplay.h1,
    lineHeight: lineHeight.tight,
    letterSpacing: "-0.02em",
  },
  h2: {
    fontFamily: fontFamily.stack,
    fontWeight: fontWeight.bold,
    fontSize: fontSizeDisplay.h2,
    lineHeight: lineHeight.tight,
    letterSpacing: "-0.015em",
  },
  h3: {
    fontFamily: fontFamily.stack,
    fontWeight: fontWeight.semibold,
    fontSize: fontSizeDisplay.h3,
    lineHeight: lineHeight.snug,
    letterSpacing: "-0.01em",
  },
  h4: {
    fontFamily: fontFamily.stack,
    fontWeight: fontWeight.semibold,
    fontSize: fontSizeDisplay.h4,
    lineHeight: lineHeight.snug,
  },
  h5: {
    fontFamily: fontFamily.stack,
    fontWeight: fontWeight.semibold,
    fontSize: fontSize.xl,
    lineHeight: lineHeight.snug,
  },
  h6: {
    fontFamily: fontFamily.stack,
    fontWeight: fontWeight.semibold,
    fontSize: fontSize["2xl"],
    lineHeight: lineHeight.snug,
    letterSpacing: "0.01em",
  },
  subtitle1: {
    fontFamily: fontFamily.stack,
    fontWeight: fontWeight.medium,
    fontSize: fontSize.lg,
    lineHeight: lineHeight.normal,
  },
  subtitle2: {
    fontFamily: fontFamily.stack,
    fontWeight: fontWeight.medium,
    fontSize: fontSize.md,
    lineHeight: lineHeight.normal,
    letterSpacing: "0.02em",
  },
  body1: {
    fontFamily: fontFamily.stack,
    fontWeight: fontWeight.base,
    fontSize: fontSize.base,
    lineHeight: lineHeight.base,
  },
  body2: {
    fontFamily: fontFamily.stack,
    fontWeight: fontWeight.base,
    fontSize: fontSize.md,
    lineHeight: lineHeight.base,
  },
  button: {
    fontFamily: fontFamily.stack,
    fontWeight: fontWeight.semibold,
    fontSize: fontSize.base,
    lineHeight: lineHeight.base,
    letterSpacing: "0.02em",
    textTransform: "none",
  },
  caption: {
    fontFamily: fontFamily.stack,
    fontWeight: fontWeight.medium,
    fontSize: fontSize.xs,
    lineHeight: lineHeight.normal,
    letterSpacing: "0.02em",
  },
  overline: {
    fontFamily: fontFamily.stack,
    fontWeight: fontWeight.bold,
    fontSize: fontSize.sm,
    lineHeight: lineHeight.normal,
    letterSpacing: "0.16em",
    textTransform: "uppercase",
  },
};
